import './index.scss';
import './js/sliders';
import './js/tab';
import './js/burger';
import './js/validation';
import './js/admin-nav-links';
import './js/modals';
import './js/animations';
import './js/breadcrumbs';
import './js/lightbox'